# Generated by Django 5.0.4 on 2024-12-03 02:07

import Access.models.Empresa
import Access.models.Producto
import Access.models.SuscripcionEmpresa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Access.models.Empresa.unique_image_path),
        ),
        migrations.AddField(
            model_name='suscripcionempresa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Access.models.SuscripcionEmpresa.unique_image_path),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Access.models.Producto.unique_image_path),
        ),
    ]
